---
- hosts: localhost
  tasks:
    - name: Log into DockerHub
      docker_login:
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
    - name: Build an image and push it to a docker hub repo
      community.docker.docker_image:
        build:
          path: "{{ workspace }}"
        name: "{{ registry_url }}"
        repository: "{{ registry_url }}:{{ version }}"
        tag: "{{ version }}"
        push: true
        source: build
    
